### ISSUE TITLE
Graylog 2.5 issues

### ISSUE THREAD

**Issue by ion-storm** [airbus-cyber/graylog-plugin-logging-alert#1]
I am getting this error:

```
2019-02-01 13:06:14.036 | graylog-1
-- | --
WARN [AlertNotificationsSender] Alarm callback <Logging Alert Notification> failed. Skipping.
```
Any ideas? I was running the internal logger plugin.

**Comment by TiNico22** [comment]
can you provide some context ?
are you using the logging plugin alone or with the others plugins installed ?

On a fresh install of graylog 2.5.1 & the 4 plugins from this repo I did get the alerts in my /var/log/graylog-server/server.log file such as the following sample with the default config after confuguration of an alert with the wizard.

 _2019-02-02T10:57:47.591+01:00 INFO  [LoggingAlert] type: alert | id: 5c55699b2d0dc33bc2cf136c | severity: high | app: graylog | subject: SUDO session not closed by user X with process Y | body: The additional stream had 0 messages with trigger condition less than 1 messages additional messages after main messages the main stream had 1 messages with trigger condition more than 0 messages in the last 1 minutes with the same value of the fields user. (Current grace time: 0 minutes) | src:  | src_category:  | dest:  | dest_category:_
