### ISSUE TITLE
logging_alert.alert_url and logging_alert.messages_url are broken in 2.x

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-logging-alert#10]
The query in logging_alert.messages_url doesn't work.
It seems it misses the part "&q=stream%3Axxxxxxxxxx":
/search?rangetype=absolute&from=aaa&to=bbb+AND+user%3Atoto

logging_alert.alert_url is always empty.
I know the page /alerts/alert_id doesn't exist anymore.
It may be possible to redirect to the page /alerts/ and to POST the right search.
If it's not possible you can remove this parameter from the code and the documentation.

**Comment by tomasnk** [comment]
The logging_alert.messages_url with missing stream part, is resolved with the aggregation and correlation plugin version 2.1.1
logging_alert.alert_url is removed in version 2.1.2 of logging alert plugin
