### ISSUE TITLE
Escape backslashes in a split field's value in the logging_alert.messages_url query

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-logging-alert#14]
The variable **logging_alert.messages_url** is a Graylog URI to retrieve logs which trigger an alert.
If you set split fields in the alert's notification, the value of the split field is included in this URI.
For example if the split field is **user** and its value for an alert is **toto**: q=user%3A%22toto%22

If this value contains backslashes they need to be escaped with another backslash otherwise the query won't find the logs on Graylog.
It often happens when you use Windows filename as split field.
The Graylog query **filename:"C:\Windows\toto.exe"** won't work, you need to escape backslashes: **filename:"C:\\\Windows\\\toto.exe"**

**Comment by c8y3** [comment]
Note: it seems character " should be escaped too

**Comment by frantz45** [comment]
I confirm it's fixed for backslash and double quotes, I close the issue
