### ISSUE TITLE
Error when viewing a notification

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-logging-alert#31]
Go to the Alerts page.
Then click on Notifications.
Click on the title of a LoggingAlert notification.
A red error message is displayed: **Notification type is not supported**.

However editing a notification works well, and the notification works too.

**Comment by c8y3** [comment]
TODO:
* update changelog

**Comment by frantz45** [comment]
I confirm it's fixed in v4.0.0.
@c8y3 You can close this issue when you will update the changelog

**Comment by c8y3** [comment]
Thank you. All done.
