### ISSUE TITLE
Configuration is not well displayed

### ISSUE THREAD

**Issue by frantz45** [airbus-cyber/graylog-plugin-logging-alert#44]
Steps to reproduce:

1. Go to System / Configuration
2. Configure Logging Alert Notification Configuration (for example juste add a word in the Log Content)
3. Close your web browser
4. Open you web browser
5. Go to System / Configuration
6. Logging Alert Notification Configuration is wrong, it displays the old configuration
7. Something funny: Click on Configure and click Cancel: The good configuration appears!

(It is just a display issue, in MongoDB the configuration is good, and when you create a new rule the good logging configuration is applied)

Environment:

- Graylog v4.3.11
- LoggingAlert v4.2.0
- Firefox 91.6 ESR

**Comment by c8y3** [comment]
The request to get the configuration values seems to be correct too. So it's probably a pure interface issue.

**Comment by c8y3** [comment]
Note: instead of closing the browser, just refreshing the page exhibits the same bug

**Comment by frantz45** [comment]
I've tested with Wizard v5.1.0 and I confirm it's fixed
